export const FETCH_START = 'MUI_THEME/FETCH_START';
export const FETCH_END = 'MUI_THEME/FETCH_END';
export const FETCH_ERROR = 'MUI_THEME/FETCH_ERROR';
export const FETCH_CANCEL = 'MUI_THEME/FETCH_CANCEL';
